# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# --file /myapp
#mvn -B package -f /home/runner/work/maven-hello-world/maven-hello-world/myapp/pom.xml

name: Java CI with Maven - Rafael 

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Increase app vervion
      run: |
        cd my-app
        mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
        MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo $MVN_VERSION
        java -cp target/classes com.mycompany.app.App
        mkdir artifact-app && cp target/*.jar artifact-app 
      
    - name: Build hello-world app
      run: |
        cd myapp
        mvn -B package

   

      
